version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nosprintfhostport
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/simplesurance/goordinator
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
