[[rule]]
  name = "trigger-ci-jobs"
  event_source = "github"
  filter_query = '''
.repository.name == "testrepo" and (
  .action == "synchronize" and ([.pull_request.labels[].name] | map(select(. == "ci")) | length) > 0
) or (
  .action == "labeled" and .label.name == "ci"
)
'''

# All actions are executed in parallel and retried on errors
  [[rule.action]]
    action = "httprequest"
    url = "https://myjenkins/view/CI/job/checks/view/change-requests/job/PR-{{ .Event.PullRequestNr }}/build"
    user = "fho"
    password = "<token>"

  [[rule.action]]
    action = "httprequest"
    url = "https://circleci.com/api/v2/project/gh/goordinator/checks/pipeline"
    user = "<token">
    headers = { "content-type" = "application/json" }
    data = '''
    {
      "branch": "pull/14380/head"
    }
    '''
